url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tim - Zheng LUO" # the name of your site, e.g. ACME Corp.
description: >
  Zheng /zɛn/ LUO 罗峥 also going by Tim,\n
  as I strive to be a <a href='https://www.bible.com/bible/59/2TI.1.7'>helpful companion</a>."
